name: "infra preview & deploy"
on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  preview:
    name: "preview"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello world"
